#!/bin/sh
#set -x

INSTALL_BINS="/Applications/CellframeNode.app/Contents/MacOS/"
INSTALL_RES=/Applications/CellframeNode.app/Contents/Resources
USER_RES="/Library/Application Support/CellframeNode" 

mkdir -p "${USER_RES}/"
cp -r "${INSTALL_RES}/etc" "${USER_RES}/"
cp -r "${INSTALL_RES}/share" "${USER_RES}/"

mkdir "${USER_RES}/var/run/"

${INSTALL_BINS}/cellframe-node-config -i "${USER_RES}/share/default.setup"

echo "[!] Set cfg permissions"
#set rwo permissions to configs
chmod 666 $(find "${USER_RES}/" -type f)
#set rwx permissions to dirs
chmod 777 $(find "${USER_RES}/" -type d)

echo "[!] Copy daemon plist"
cp ${INSTALL_RES}/com.demlabs.cellframe-node.plist /Library/LaunchDaemons/

${INSTALL_BINS}/cellframe-node-config -e service enable
