
build_dependencies:
  deb:
    - 'build-essential'
    - 'cmake'
    - 'libmagic-dev'
    - 'libsqlite3-dev'
    - 'libjson-c-dev' 
    - 'python3-dev'
    - 'file'
    

pack_dependencies:
  deb:
    - 'cmake'
    - 'file'
    