#!/bin/bash -e

case "$1" in
	remove|purge|abort-install|abort-upgrade)
		echo "[*] Stopping cellframe-node and services..."
		systemctl stop cellframe-node.service || true
		systemctl stop cellframe-updater.service || true

		echo "[*] Disabling cellframe-node and services..."
		systemctl disable cellframe-node.service || true
		systemctl disable cellframe-updater.service || true

		;;

	disappear)
		;;

	upgrade)
		echo "[*] Stopping cellframe-node and services..."
        systemctl stop cellframe-node.service || true
        systemctl stop cellframe-updater.service || true
		;;

	failed-upgrade)
		echo "[*] Stopping cellframe-node and services"
        systemctl stop cellframe-node.service || true
        systemctl stop cellframe-updater.service || true
        ;;

	*)
	    echo "prerm called with unknown argument \`$1'" >&2
		exit 1;;
esac

exit 0
