#!/bin/sh

echo "Creating the new user for dapserver authorization"

read -p "Enter login: " login
if [ -z "$login" ]; then
    echo "[CRITICAL] Need username to create new login record in the database"
    exit 1
fi

result=$(mongo dapDb --eval "db.dap_users.find( { login : \"${login}\" } )" | wc -l)

if [ $result -eq 2 ]; then 
	echo "Login not found in DataBase"
	exit 2
fi

read -p "Enter new password: " password
if [ -z "$password" ]; then
    echo "[CRITICAL] Need secure password to create new login record in the database"
    exit 3
fi

salt=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 8; echo '')

echo -n "${password}${salt}" | openssl dgst -sha512 -binary > temp.txt
echo -n "${salt}" | openssl dgst -sha512 -binary >> temp.txt
b64=$(cat temp.txt | base64)
b64urlstring=$(echo $b64 | tr "+/" "-_" | tr -d ' =')
b64salt=$(echo -n ${salt} | base64 | tr "+/" "-_" | tr -d ' =')
rm temp.txt

mongo dapDb --eval "db.dap_users.update( { login : \"${login}\"}, { \$set: { passwordHash : \"${b64urlstring}\", salt : \"${b64salt}\"  } } )"




