#!/bin/sh

echo "Creating the new user for dapserver authorization"

if [ $# -eq 1 ]; then
	echo "Need two parametrs ( email and password )"
	exit 5
fi

if [ $# -eq 2 ]; then

	email=$1
	password=$2

	is_correct_email=$(echo $email | grep -E "^.+@.+[.].+$")
	if [ -z $is_correct_email ]; then
		echo Error! Bad email address. Use first parametr email, second - password
		exit 4
	fi
else
 
	read -p "Enter login: " login
	if [ -z "$login" ]; then
    		echo "[CRITICAL] Need username to create new login record in the database"
    		exit 1
	fi

	read -p "Enter password: " password
	if [ -z "$password" ]; then
    		echo "[CRITICAL] Need secure password to create new login record in the database"
    		exit 2
	fi

	read -p "Enter email: " email

	if [ -n "$email" ]; then 
		is_correct_email=$(echo $email | grep -E "^.+@.+[.].+$")
		if [ -z $is_correct_email ]; then
			echo Error! Bad email address.
			exit 4
		fi
	fi

	read -p "Enter first_name ( can skip ): " first_name	
	read -p "Enter last_name ( can skip ): " last_name
	
fi

domain=klvn.io

mongodomain=`mongo dapDb --eval "db.dap_domains.distinct( \"_id\", { domain : \"$domain\" })" `
mongodomain=`echo "$mongodomain" | tail -1 | tr -d "[] "`

if [ -z $mongodomain ]; then
	echo "domain not find in database"
	exit 3
else

fi

password_hash=$(/opt/cellframe-node/bin/dap_server_http_db_auth_tool password_hash ${password})
echo "Password hash $password_hash"
if [ -z "$login" ]; then
	login=$email
fi

if [ -z "$email" ]; then
    email=$login
fi

registration_date=$(date -u "+%Y-%m-%d %T")
expired_date=$(date -u -d '+ 3 day' '+%Y-%m-%d %T')

mongo dapDb --eval "db.dap_users.insert( { login : \"${login}\", email : \"${email}\", passwordHash : \"${password_hash}\",\
domainId : ${mongodomain}, profile: { first_name : \"${first_name}\",\
last_name : \"${last_name}\" }, registration_date : ISODate(\"${registration_date}\"), expire_date : ISODate(\"${expired_date}\"), contacts: [] } )"

