#!/bin/sh

: 'Выдача подписки клиенту. Входные данные: логин и количество дней на которое
выписывается/продляется подписка, ( отсчет идет от момента использования скрипта, если 
подписка еще активная то продляется на N дней )'

echo "Set user subscription"

if [ $# -ne "2" ]; then
	echo "Error! Need two parametrs login(email?) and count day's subscribtion"
	exit 1
fi

result=$(mongo dapDb --eval "db.dap_users.find( { login : \"${1}\" } )" | wc -l)

if [ $result -eq 2 ]; then 
	echo "Login not found in DataBase"
	exit 2
fi

iso_date_expire=$(mongo dapDb --eval "db.dap_users.find( { login: \"${1}\" }, { expire_date : 1, _id : 0 } )" )
iso_date_expire=$(echo $iso_date_expire | grep -E -o "ISODate.+)" | grep -E -o "[0-9]+.+Z") 

iso_date_expire_in_sec=$(date -d $iso_date_expire "+%s")
now_date_in_sec=$(date "+%s")

date_diff=`expr $iso_date_expire_in_sec - $now_date_in_sec`

if [ $date_diff -lt 0 ]; then
	result_date=$(date -u -d '+ '${2}' day' '+%Y-%m-%d %T')
else
	result_date=$(date -u -d "$iso_date_expire + ${2} day" "+%Y-%m-%d %T")	
fi  

mongo dapDb --eval "db.dap_users.update( { login : \"${1}\"}, { \$set: { expire_date : ISODate(\"${result_date}\") }} )"

echo "Subscription update for client to: " $result_date

